### ISSUE TITLE
Session not started yet

### ISSUE THREAD

**Issue by maxmasetti** [loadsys/CakePHP-CreatorModifier#15]
hi,
I installed the plugin but verified it does't work I found that on line 168
`$request->session()->started()`
doesn't return true, commented the if clause it works properly.
can you help me?
thanks

**Comment by justinyost** [comment]
Hi @maxmasetti,

Thanks for the issue notice.

So typically this happens because you are trying to save a record when you don't have the session started for Cake. Typically you'll need to trigger the session to start. A good solution to this is to enable the Flash or Auth components. Let me know if that helps.

**Comment by justinyost** [comment]
Also, I'm adding an issue to add some better handling around this specific case, https://github.com/loadsys/CakePHP-CreatorModifier/issues/16

**Comment by maxmasetti** [comment]
Hi, I'm using cakedc/users plugin to manage auth and it works. So I can't understand why the session isn't started yet when creator behaviour is called.

max

**Comment by justinyost** [comment]
Hmm, that's fun. I'm not sure why it isn't working then. I can tell you I know the cause of the issue, which is the session not being started. I'm not sure I can give you a reason why that is true however.

I'll work on trying to have an update out for you that should resolve this per Issue #16.

**Comment by maxmasetti** [comment]
digging deeply, I found session is in PHP_SESSION_NONE status (i.e. not disabled but not active (yet?)). but `$request->session()->read()` returns the correct value.

**Comment by justinyost** [comment]
So is a User currently logged in at this point? If a User is not logged in, the Session is not active at which point there is no `Auth.User.id` value to return.

**Comment by maxmasetti** [comment]
Yes, the user is logged in and grabbing values (at line 167 of Creator):

```
var_dump($request->session()->started());
var_dump($request->session()->read($this->_config['sessionUserIdKey']));
die;
```

gives:

```
bool(false) int(1)
```

quite illogic!

**Comment by justinyost** [comment]
Uh, that's interesting.

**Comment by justinyost** [comment]
@maxmasetti If you have the ability/time to try out a branch that hopefully should fix this issue, that would be great: https://github.com/loadsys/CakePHP-CreatorModifier/pull/17

**Comment by maxmasetti** [comment]
now I'm working on a big project and no time to spend on this. may be in the future
