### ISSUE TITLE
Does README need to mention `Plugin->load('CreatorModifier')`?

### ISSUE THREAD

**Issue by beporter** [loadsys/CakePHP-CreatorModifier#8]

**Comment by TheFRedFox** [comment]
It's old now, but I would say "yes". It is just a small addition, but it is helping newbies a lot. Also for consistency in the "Usage" section, I would say, you can just use it, if you also loaded the plugin. :wink:

**Comment by beporter** [comment]
👍  This should be resolved once #14 is merged.
